### ISSUE TITLE
Style social icons

### ISSUE THREAD

**Issue by Wryhder** [sarscode/hng-dragonslayers#40]
Medium, Twitter and Github icons

**Comment by cassyblaise** [comment]
@Wryhder  please can assign this to me

**Comment by Wryhder** [comment]
@cassyblaise Ask @sarscode for access to this repo and you can assign yourself on the right.

**Comment by cassyblaise** [comment]
@Wryhder I just fork this: https://github.com/hng5-blog-task/hng-dragonslayers.git can i assign any of the project to myself?

**Comment by cassyblaise** [comment]
@sarscode please can you assign any of the project for me?

**Comment by Wryhder** [comment]
@cassyblaise Go on Slack, DM @sars and give him your github username. That way, you can assign yourself an issue on this repo, not your fork, and others can see that someone else is already working on it.
You make the changes on your fork and create a PR against the development branch here.

**Comment by aniekanedet** [comment]
I'd like to 

> Medium, Twitter and Github icons

I'll work on this
