### ISSUE TITLE
Login Page: Add markup for "Welcome Back"  text

### ISSUE THREAD

**Issue by oyewoas** [sarscode/hng-dragonslayers#57]
Add the Markup for the "Welcome Back" text as seen in the  UI/UX design, please follow the design structure. part is highlighted below.
![welcome](https://user-images.githubusercontent.com/31412106/55669590-2235a300-5871-11e9-81b9-804b9e845bae.png)

**Comment by peli95** [comment]
I would like to work on this.Please assign it to me
