### ISSUE TITLE
Login Page: Add markup for "Sign In using Google" Button

### ISSUE THREAD

**Issue by oyewoas** [sarscode/hng-dragonslayers#58]
Add the Markup for the "Sign In using Google" Button as seen in the UI/UX design, please follow the design structure. part is highlighted below.
![signingoogle](https://user-images.githubusercontent.com/31412106/55669579-05996b00-5871-11e9-8c5f-481c8fa5f07b.png)

**Comment by Mr-Malomz** [comment]
Hey Brov,

I can write the markup for this. Assign it to me and I will start immediately.
