### ISSUE TITLE
Login Page: Add markup for "Sign In using Facebook" Button

### ISSUE THREAD

**Issue by oyewoas** [sarscode/hng-dragonslayers#59]
Add the Markup for the "Sign In using Facebook" Button  as seen in the UI/UX design, please follow the design structure. part is highlighted below
![signinfacebook](https://user-images.githubusercontent.com/31412106/55669567-cc60fb00-5870-11e9-9717-a67ca8d22670.png)

**Comment by seyicole** [comment]
I’ll work on this

**Comment by seyicole** [comment]
@Wryhder I dont think i've the priviledge to assign myself a task

**Comment by Wryhder** [comment]
Ask @sars on Slack.
