### ISSUE TITLE
Create container element for names

### ISSUE THREAD

**Issue by Wryhder** [sarscode/hng-dragonslayers#7]

**Comment by Thobeats** [comment]
pls can u explain a bit? container element for what "names"?

**Comment by Wryhder** [comment]
@Thobeats The name of the owner/user on the left. right under the profile image.
![HNGI5 Design Team Task](https://user-images.githubusercontent.com/21000445/55668885-ca466e80-5867-11e9-8092-73d561f2172a.png)

**Comment by Thobeats** [comment]
Alright i will do this

**Comment by Wryhder** [comment]
Please assign yourself to the issue on the right side of this page.

**Comment by Thobeats** [comment]
Still waiting for write access, thought i had the access
