### ISSUE TITLE
Manage Feed Page: Style the subscribe and unsubscribe button.

### ISSUE THREAD

**Issue by theboringdude** [sarscode/hng-dragonslayers#83]

**Comment by Adiomojeed** [comment]
I can't find any subscribe or unsubscribe button on the profile page

**Comment by theboringdude** [comment]
Sorry it is manage feeds page.

**Comment by EphraimDev** [comment]
I'm almost done with this

**Comment by Oluwatosinn** [comment]
![hng](https://user-images.githubusercontent.com/37472016/55686575-c0e9fe80-595a-11e9-9329-f455ef67d6d8.PNG)
